# Generated by Django 5.1.4 on 2025-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.TextField(blank=True, null=True)),
                ('area_name', models.CharField(max_length=255)),
                ('published_at', models.DateField()),
            ],
        ),
    ]
